import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";
import { setCloudflareBindings, type CloudflareBindings } from "../app/db.server";

// Generated by `npm run build` before Cloudflare Pages bundles this Function.
// @ts-expect-error The Remix server build is created at deploy time.
import * as build from "../build/server/index";

export const onRequest = createPagesFunctionHandler<CloudflareBindings>({
  build,
  mode: "production",
  getLoadContext({ context }) {
    setCloudflareBindings(context.cloudflare.env);
    return context;
  },
});
